USE [master]
GO
/****** Object:  Database [MyBlogDB]    Script Date: 29.11.2022 09:23:15 ******/
DROP DATABASE [MyBlogDB]
GO
/****** Object:  Database [MyBlogDB]    Script Date: 29.11.2022 09:23:15 ******/
CREATE DATABASE [MyBlogDB]
GO
ALTER DATABASE [MyBlogDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyBlogDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MyBlogDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyBlogDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MyBlogDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MyBlogDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MyBlogDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MyBlogDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyBlogDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyBlogDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyBlogDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyBlogDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MyBlogDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MyBlogDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyBlogDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MyBlogDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyBlogDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyBlogDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyBlogDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyBlogDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyBlogDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyBlogDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyBlogDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyBlogDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyBlogDB] SET RECOVERY FULL 
GO
ALTER DATABASE [MyBlogDB] SET  MULTI_USER 
GO
ALTER DATABASE [MyBlogDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MyBlogDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MyBlogDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MyBlogDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MyBlogDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MyBlogDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MyBlogDB', N'ON'
GO
ALTER DATABASE [MyBlogDB] SET QUERY_STORE = OFF
GO
USE [MyBlogDB]
GO
/****** Object:  Table [dbo].[Etiketler]    Script Date: 29.11.2022 09:23:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Etiketler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Deger] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Etiketler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EtiketYazilar]    Script Date: 29.11.2022 09:23:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EtiketYazilar](
	[YaziId] [int] NOT NULL,
	[EtiketId] [int] NOT NULL,
 CONSTRAINT [PK_EtiketYazilar] PRIMARY KEY CLUSTERED 
(
	[YaziId] ASC,
	[EtiketId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Kategoriler]    Script Date: 29.11.2022 09:23:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kategoriler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Adi] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Kategoriler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KategoriYazilar]    Script Date: 29.11.2022 09:23:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KategoriYazilar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[YaziId] [int] NOT NULL,
	[KategoriId] [int] NOT NULL,
 CONSTRAINT [PK_KategoriYazilar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Yazarlar]    Script Date: 29.11.2022 09:23:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Yazarlar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Adi] [nvarchar](50) NULL,
	[Soyadi] [nvarchar](50) NULL,
	[EPosta] [nvarchar](50) NOT NULL,
	[Sifre] [nvarchar](16) NOT NULL,
 CONSTRAINT [PK_Yazarlar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[YazarYazilar]    Script Date: 29.11.2022 09:23:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[YazarYazilar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[YazarId] [int] NOT NULL,
	[YaziId] [int] NOT NULL,
 CONSTRAINT [PK_YazarYazilar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Yazilar]    Script Date: 29.11.2022 09:23:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Yazilar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Baslik] [nvarchar](150) NOT NULL,
	[Aciklama] [nvarchar](max) NULL,
	[YayinlanmaTarihi] [datetime] NOT NULL,
	[GuncellenmeTarihi] [datetime] NULL,
	[YayindaMi] [bit] NOT NULL,
 CONSTRAINT [PK_Yazilar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Yorumlar]    Script Date: 29.11.2022 09:23:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Yorumlar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Yorum] [nvarchar](500) NOT NULL,
	[Tarihi] [datetime] NOT NULL,
	[YaziId] [int] NOT NULL,
 CONSTRAINT [PK_Yorumlar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Yazilar] ADD  CONSTRAINT [DF_Yazilar_YayindaMi]  DEFAULT ((0)) FOR [YayindaMi]
GO
ALTER TABLE [dbo].[EtiketYazilar]  WITH CHECK ADD  CONSTRAINT [FK_EtiketYazilar_Etiketler] FOREIGN KEY([EtiketId])
REFERENCES [dbo].[Etiketler] ([Id])
GO
ALTER TABLE [dbo].[EtiketYazilar] CHECK CONSTRAINT [FK_EtiketYazilar_Etiketler]
GO
ALTER TABLE [dbo].[EtiketYazilar]  WITH CHECK ADD  CONSTRAINT [FK_EtiketYazilar_Yazilar] FOREIGN KEY([YaziId])
REFERENCES [dbo].[Yazilar] ([Id])
GO
ALTER TABLE [dbo].[EtiketYazilar] CHECK CONSTRAINT [FK_EtiketYazilar_Yazilar]
GO
ALTER TABLE [dbo].[KategoriYazilar]  WITH CHECK ADD  CONSTRAINT [FK_KategoriYazilar_Kategoriler] FOREIGN KEY([KategoriId])
REFERENCES [dbo].[Kategoriler] ([Id])
GO
ALTER TABLE [dbo].[KategoriYazilar] CHECK CONSTRAINT [FK_KategoriYazilar_Kategoriler]
GO
ALTER TABLE [dbo].[KategoriYazilar]  WITH CHECK ADD  CONSTRAINT [FK_KategoriYazilar_Yazilar] FOREIGN KEY([YaziId])
REFERENCES [dbo].[Yazilar] ([Id])
GO
ALTER TABLE [dbo].[KategoriYazilar] CHECK CONSTRAINT [FK_KategoriYazilar_Yazilar]
GO
ALTER TABLE [dbo].[YazarYazilar]  WITH CHECK ADD  CONSTRAINT [FK_YazarYazilar_Yazarlar] FOREIGN KEY([YazarId])
REFERENCES [dbo].[Yazarlar] ([Id])
GO
ALTER TABLE [dbo].[YazarYazilar] CHECK CONSTRAINT [FK_YazarYazilar_Yazarlar]
GO
ALTER TABLE [dbo].[YazarYazilar]  WITH CHECK ADD  CONSTRAINT [FK_YazarYazilar_Yazilar] FOREIGN KEY([YaziId])
REFERENCES [dbo].[Yazilar] ([Id])
GO
ALTER TABLE [dbo].[YazarYazilar] CHECK CONSTRAINT [FK_YazarYazilar_Yazilar]
GO
ALTER TABLE [dbo].[Yorumlar]  WITH CHECK ADD  CONSTRAINT [FK_Yorumlar_Yazilar] FOREIGN KEY([YaziId])
REFERENCES [dbo].[Yazilar] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Yorumlar] CHECK CONSTRAINT [FK_Yorumlar_Yazilar]
GO
USE [master]
GO
ALTER DATABASE [MyBlogDB] SET  READ_WRITE 
GO
