USE [master]
GO
/****** Object:  Database [MRentACarDB]    Script Date: 29.11.2022 10:34:38 ******/
CREATE DATABASE [MRentACarDB]
GO
ALTER DATABASE [MRentACarDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MRentACarDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MRentACarDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MRentACarDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MRentACarDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MRentACarDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MRentACarDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MRentACarDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MRentACarDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MRentACarDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MRentACarDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MRentACarDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MRentACarDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MRentACarDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MRentACarDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MRentACarDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MRentACarDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MRentACarDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MRentACarDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MRentACarDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MRentACarDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MRentACarDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MRentACarDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MRentACarDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MRentACarDB] SET RECOVERY FULL 
GO
ALTER DATABASE [MRentACarDB] SET  MULTI_USER 
GO
ALTER DATABASE [MRentACarDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MRentACarDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MRentACarDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MRentACarDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MRentACarDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MRentACarDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MRentACarDB', N'ON'
GO
ALTER DATABASE [MRentACarDB] SET QUERY_STORE = OFF
GO
USE [MRentACarDB]
GO
/****** Object:  Table [dbo].[Araclar]    Script Date: 29.11.2022 10:34:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Araclar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ModelID] [int] NOT NULL,
	[KM] [int] NOT NULL,
	[Yili] [smallint] NOT NULL,
	[KiralanabilirMi] [bit] NOT NULL,
	[GunlukKiraBedeli] [decimal](8, 2) NOT NULL,
	[Resim] [nvarchar](260) NULL,
 CONSTRAINT [PK_Araclar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Kiralamalar]    Script Date: 29.11.2022 10:34:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Kiralamalar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AracID] [int] NOT NULL,
	[MusteriID] [int] NOT NULL,
	[BaslangicTarihi] [datetime] NOT NULL,
	[BitisTarihi] [datetime] NOT NULL,
	[Kaparo] [decimal](8, 2) NOT NULL,
	[Aciklama] [nvarchar](500) NULL,
 CONSTRAINT [PK_Kiralamalar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Markalar]    Script Date: 29.11.2022 10:34:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Markalar](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Adi] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Markalar] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MarkalarModeller]    Script Date: 29.11.2022 10:34:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MarkalarModeller](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Adi] [nvarchar](50) NOT NULL,
	[Tip] [char](2) NOT NULL,
	[ParentID] [int] NULL,
 CONSTRAINT [PK_MarkalarModeller] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Modeller]    Script Date: 29.11.2022 10:34:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Modeller](
	[Id] [int] NOT NULL,
	[Adi] [nvarchar](50) NOT NULL,
	[MarkaID] [int] NOT NULL,
 CONSTRAINT [PK_Modeller] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Musteriler]    Script Date: 29.11.2022 10:34:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Musteriler](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Adi] [nvarchar](50) NOT NULL,
	[Soyadi] [nvarchar](50) NOT NULL,
	[TCNo] [char](11) NOT NULL,
 CONSTRAINT [PK_Musteriler] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Markalar]    Script Date: 29.11.2022 10:34:38 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Markalar] ON [dbo].[Markalar]
(
	[Adi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Araclar] ADD  CONSTRAINT [DF_Araclar_KM]  DEFAULT ((0)) FOR [KM]
GO
ALTER TABLE [dbo].[Araclar] ADD  CONSTRAINT [DF_Araclar_KiralanabilirMi]  DEFAULT ((1)) FOR [KiralanabilirMi]
GO
ALTER TABLE [dbo].[Araclar]  WITH CHECK ADD  CONSTRAINT [FK_Araclar_Modeller] FOREIGN KEY([ModelID])
REFERENCES [dbo].[Modeller] ([Id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Araclar] CHECK CONSTRAINT [FK_Araclar_Modeller]
GO
ALTER TABLE [dbo].[Kiralamalar]  WITH CHECK ADD  CONSTRAINT [FK_Kiralamalar_Araclar] FOREIGN KEY([AracID])
REFERENCES [dbo].[Araclar] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Kiralamalar] CHECK CONSTRAINT [FK_Kiralamalar_Araclar]
GO
ALTER TABLE [dbo].[Kiralamalar]  WITH CHECK ADD  CONSTRAINT [FK_Kiralamalar_Musteriler] FOREIGN KEY([MusteriID])
REFERENCES [dbo].[Musteriler] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Kiralamalar] CHECK CONSTRAINT [FK_Kiralamalar_Musteriler]
GO
ALTER TABLE [dbo].[MarkalarModeller]  WITH CHECK ADD  CONSTRAINT [FK_MarkalarModeller_MarkalarModeller] FOREIGN KEY([ParentID])
REFERENCES [dbo].[MarkalarModeller] ([Id])
GO
ALTER TABLE [dbo].[MarkalarModeller] CHECK CONSTRAINT [FK_MarkalarModeller_MarkalarModeller]
GO
ALTER TABLE [dbo].[Modeller]  WITH CHECK ADD  CONSTRAINT [FK_Modeller_Markalar] FOREIGN KEY([MarkaID])
REFERENCES [dbo].[Markalar] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Modeller] CHECK CONSTRAINT [FK_Modeller_Markalar]
GO
USE [master]
GO
ALTER DATABASE [MRentACarDB] SET  READ_WRITE 
GO
